### ISSUE TITLE
core dump while running example

### ISSUE THREAD

**Issue by sshsu** [qicosmos/cinatra#145]
here is a core dump stack while I running cinatra_example
```
Thread 1 "cinatra_example" received signal SIGSEGV, Segmentation fault.
0x0000555555746f0c in std::__shared_ptr<std::__future_base::_State_baseV2, (__gnu_cxx::_Lock_policy)2>::__shared_ptr (this=0x7fffffffde00) at /usr/include/c++/7/bits/shared_ptr_base.h:1121
1121          __shared_ptr(const __shared_ptr&) noexcept = default;
(gdb) bt
#0  0x0000555555746f0c in std::__shared_ptr<std::__future_base::_State_baseV2, (__gnu_cxx::_Lock_policy)2>::__shared_ptr (this=0x7fffffffde00) at /usr/include/c++/7/bits/shared_ptr_base.h:1121
#1  0x0000555555746f57 in std::shared_ptr<std::__future_base::_State_baseV2>::shared_ptr (this=0x7fffffffde00) at /usr/include/c++/7/bits/shared_ptr.h:119
#2  0x0000555555764d3e in std::__basic_future<std::tuple<cinatra::error_code, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::__basic_future (this=0x7fffffffde00, 
    __state=<error reading variable: Cannot access memory at address 0x8>) at /usr/include/c++/7/future:730
#3  0x0000555555759a63 in std::future<std::tuple<cinatra::error_code, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::future (this=0x7fffffffde00, 
    __state=<error reading variable: Cannot access memory at address 0x8>) at /usr/include/c++/7/future:773
#4  0x000055555574cedb in std::promise<std::tuple<cinatra::error_code, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::get_future (this=0x0)
    at /usr/include/c++/7/future:1105
#5  0x00005555557413fc in cinatra::http_client::request (this=0x555555a63b10, method=cinatra::http_method::GET, uri="", body="", seconds=5) at /root/git/cinatra/example/../include/cinatra/http_client.hpp:167
#6  0x0000555555740688 in cinatra::http_client::get (this=0x555555a63b10, uri="", seconds=5) at /root/git/cinatra/example/../include/cinatra/http_client.hpp:99
#7  0x000055555571bb0b in test_client () at /root/git/cinatra/example/main.cpp:60
#8  0x000055555571c234 in main () at /root/git/cinatra/example/main.cpp:99
```
what causes this is shared_ptr promise_ is nullptr,  in stack 5, I print **promise_** and find **promise_->get()** is 0x0
```
(gdb) f 5
#5  0x00005555557413fc in cinatra::http_client::request (this=0x555555a63b10, method=cinatra::http_method::GET, uri="", body="", seconds=5) at /root/git/cinatra/example/../include/cinatra/http_client.hpp:167
167                     auto future = promise_->get_future();
(gdb) p promise_ 
$1 = std::shared_ptr<std::promise<std::tuple<cinatra::error_code, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >> (empty) = {get() = 0x0}
```
obviously, function async_request() sets **promise_** to nullptr, and my program run **async_connect(std::move(ctx), nullptr);**  following up
```
        error_code async_request(http_method method, std::string uri, callback_t cb, std::string body="") {
            if (method != http_method::POST&&!body.empty()) {
                return error_code::invalid_method;
            }
            auto [code, u] = get_uri(uri);
            if (code != error_code::success) {
                return code;
            }
            cb_ = std::move(cb);
          if (promise_) {     
=>              promise_ = nullptr;
            }
            context ctx(u, method, std::move(body));
            if (!has_connected_) {
=>              async_connect(std::move(ctx), nullptr);
            }
            else {
                send_msg(ctx);
            }

            return error_code::success;
        }
```
maybe **pomise_** will be changed in following-up function, But I am not familiar with c++ and asio,  so I cannot figure out why pomise_  was not assigned correctly, and I comment **promise_ = nullptr;**,  a http get request will correctly work

commit id:  9b2cc51c7563ca3b984bd1bd66113aa0822dfcd4

**Comment by sshsu** [comment]
update to newest version: 6064b17e212536c3c0e8248a10377b391ffa0725 fix this problem
